#ifndef READHWCONFIGFILE_GLOBAL_H
#define READHWCONFIGFILE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(READHWCONFIGFILE_LIBRARY)
#  define READHWCONFIGFILESHARED_EXPORT Q_DECL_EXPORT
#else
#  define READHWCONFIGFILESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // READHWCONFIGFILE_GLOBAL_H
